// DOM emulation, not a real-browser rendering/accessibility certification.
import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync}from'node:fs';import {webcrypto}from'node:crypto';import {JSDOM}from'jsdom';import * as core from'../dist/core.mjs';import * as studyCore from'../dist/study-core.mjs';
const bytes=readFileSync(new URL('../dist/data/information.json',import.meta.url));const data=JSON.parse(bytes);const read=f=>readFileSync(new URL('../dist/'+f,import.meta.url),'utf8');
async function setup(page,script,query=''){
 const dom=new JSDOM(read(page),{url:'https://test.invalid/'+page+query,runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;
 Object.assign(w,core,studyCore,{e:core.escapeHTML,structuredClone,TextDecoder,Blob,fetch:async()=>({ok:true,json:async()=>structuredClone(data),arrayBuffer:async()=>bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength)})});Object.defineProperty(w.crypto,'subtle',{value:webcrypto.subtle});w.confirm=()=>true;w.print=()=>{};
 w.HTMLAnchorElement.prototype.click=function(){};w.URL.createObjectURL=blob=>{w.__blob=blob;return 'blob:testing';};w.URL.revokeObjectURL=()=>{};
 let code=read(script).replace(/^import .*?;\n/,'').replace(/^import\{[^\n]+;\n/,'');code=code.replace(/\ninit\(\);\s*$/,'\nwindow.__ready=init();');w.eval(code);if(w.__ready)await w.__ready;return dom;
}
const tick=w=>new Promise(resolve=>w.setTimeout(resolve,5));
test('resident journey: category, detail, source, back preserves filter and focus',async()=>{const d=await setup('index.html','app.mjs','?study=1');const w=d.window,q=s=>w.document.querySelector(s);try{assert.equal(w.document.querySelectorAll('.card').length,10);const waste=q('[data-category=waste]');waste.focus();waste.click();assert.equal(w.document.querySelectorAll('.card').length,3);assert.equal(w.document.activeElement.dataset.category,'waste');w.location.hash='#detail/bulky-waste';await tick(w);assert.match(q('#detail h1').textContent,/粗大/);assert.equal(q('[data-source]').href,data.items.find(r=>r.id==='bulky-waste').sourceUrl);assert.equal(q('[data-source]').target,'_blank');assert.equal(q('[data-source]').dispatchEvent(new w.MouseEvent('click',{cancelable:true})),false);assert.equal(q('a[href^="tel:"]').dispatchEvent(new w.MouseEvent('click',{cancelable:true})),false);w.location.hash='';await tick(w);assert.equal(w.document.querySelectorAll('.card').length,3);assert.equal(w.document.activeElement.id,'link-bulky-waste');}finally{w.close();}});
test('search empty state, text settings, contrast, unsupported audio',async()=>{const d=await setup('index.html','app.mjs','?study=1');const w=d.window,q=s=>w.document.querySelector(s);try{q('#query').value='nothinghere';q('#search').dispatchEvent(new w.Event('submit',{cancelable:true}));assert.ok(q('#empty-reset'));q('#empty-reset').click();assert.equal(w.document.querySelectorAll('.card').length,10);q('[data-size-button=largest]').click();assert.equal(w.document.documentElement.dataset.size,'largest');q('#contrast').click();assert.ok(w.document.documentElement.classList.contains('high'));w.location.hash='#detail/city-office';await tick(w);q('#speak').click();assert.match(q('#speech-status').textContent,/利用できません/);}finally{w.close();}});
test('baseline hides treatment controls but retains all data and detail content',async()=>{const d=await setup('index.html','app.mjs','?study=1&view=baseline');const w=d.window;try{assert.equal(w.document.querySelectorAll('.base-list li').length,10);assert.equal(w.document.querySelector('#search').hidden,true);w.location.hash='#detail/machi-hokenshitsu';await tick(w);assert.match(w.document.querySelector('#detail').textContent,/16:30|16時30分/);}finally{w.close();}});
test('editor refuses unsafe source and exports valid changes without HTML execution',async()=>{const d=await setup('editor.html','editor.mjs');const w=d.window,q=s=>w.document.querySelector(s);try{q('#f-sourceUrl').value='javascript:alert(1)';q('#export').click();assert.match(q('#message').textContent,/出典URL/);assert.equal(w.__blob,undefined);q('#f-sourceUrl').value=data.items[0].sourceUrl;q('#f-title').value='<img src=x onerror=alert(1)>';q('#export').click();const out=JSON.parse(await w.__blob.text());assert.equal(out.items[0].title,'<img src=x onerror=alert(1)>');assert.equal(w.document.querySelector('#records img'),null);}finally{w.close();}});
test('study runs six practice tasks, records actions and exports a coherent crossover',async()=>{const d=await setup('study.html','study.mjs');const w=d.window,q=s=>w.document.querySelector(s);try{q('#pid').value='P002';q('#consent').checked=true;await q('#setup').onsubmit(new w.Event('submit',{cancelable:true}));for(let i=0;i<6;i++){q('#start').click();const source=q('#frame').contentWindow;w.dispatchEvent(new w.MessageEvent('message',{origin:w.location.origin,source,data:{type:'nabari-action',action:'ready'}}));assert.equal(q('#finish').hidden,false);w.dispatchEvent(new w.MessageEvent('message',{origin:w.location.origin,source,data:{type:'nabari-action',action:'detail',id:'city-office'}}));q('[data-outcome=success]').click();}assert.equal(q('#done').hidden,false);q('#save').click();const out=JSON.parse(await w.__blob.text());assert.equal(out.complete,true);assert.equal(out.dataKind,'practice');assert.equal(out.records.length,6);assert.equal(out.records[0].condition,'baseline');assert.equal(out.records[3].condition,'enhanced');assert.equal(out.records[0].actions.length,1);assert.match(out.datasetSha256,/^[a-f0-9]{64}$/);}finally{w.close();}});
